# -*- coding: utf-8 -*-
"""rural_indicaters1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BiPcVOLQTFxIIqVelaE5tnwGn6_HcAAD
"""
"""Rural WASH Indicators & Fetal Mortality - Data Analysis

This notebook explores the relationship between WASH (Water, Sanitation, and Hygiene) indicators 
and fetal mortality rates in rural regions across countries.

Key steps performed:
1. Dataset import & preview
2. Column checks & renaming for clarity
3. Merging WASH & fetal mortality datasets
4. Cleaning & preprocessing
5. Exploratory scatter plot: sanitation vs fetal mortality
6. Random Forest model to evaluate importance of WASH factors
7. Feature importance visualization""" 


# -------------------------------
# Import Libraries
# -------------------------------
   
from google.colab import files
uploaded = files.upload()

import pandas as pd
import matplotlib.pyplot as plt
# -------------------------------
# Upload & Load Datasets
# -------------------------------

# Load CSVs (replace names if needed)
wash = pd.read_csv("rural_indicators.csv")
fetal = pd.read_csv("fetal_mortality.csv")

print("WASH Data Preview:")
display(wash.head())

print("\nFetal Mortality Data Preview:")
display(fetal.head())

 #  Inspect Available Columns)
 
print("\nColumns in WASH data:", wash.columns.tolist())
print("\nColumns in Fetal data:", fetal.columns.tolist())

df = pd.merge(wash, fetal, on=["country", "year"], how="inner")
df.head()

print("WASH columns:")
print(wash.columns.tolist())

print("\nFetal Mortality columns:")
print(fetal.columns.tolist())

# Split "country_year" into two columns: country & year
wash[['country', 'year']] = wash['country_year'].str.split('_', n=1, expand=True)

# Convert year column to numeric (just in case)
wash['year'] = pd.to_numeric(wash['year'], errors='coerce')

fetal['year'] = pd.to_numeric(fetal['date'], errors='coerce')

# ✅ Preprocessing & Merging

df = pd.merge(
    wash, fetal,
    on=['subgroup','year'],
    how='inner'
)

df.head()

df = df.rename(columns={
    'Population using basic sanitation services (%)': 'basic_sanitation',
    'estimate': 'fetal_mortality_rate'
})

import matplotlib.pyplot as plt

plt.figure(figsize=(6,4))
plt.scatter(df['basic_sanitation'], df['fetal_mortality_rate'])
plt.xlabel("Basic Sanitation Access (%)")
plt.ylabel("Fetal Mortality Rate")
plt.title("Sanitation Access vs. Fetal Mortality")
plt.show()

df.shape
df.head()

print(df.columns)
df[['basic_sanitation', 'fetal_mortality_rate']].describe()

df[['basic_sanitation', 'fetal_mortality_rate']].isna().sum()

print(df['basic_sanitation'].unique()[:10])
print(df['fetal_mortality_rate'].unique()[:10])

for col in wash.columns:
    print(col)

Population using basic sanitation services (%)

wash = wash.rename(columns={
    'Population using basic sanitation services (%)': 'basic_sanitation',
    'fetal_mortality_country_avergage': 'fetal_mortality_rate'
})

wash_clean = wash.dropna(subset=['basic_sanitation','fetal_mortality_rate'])

import matplotlib.pyplot as plt

plt.figure(figsize=(6,4))
plt.scatter(wash_clean['basic_sanitation'], wash_clean['fetal_mortality_rate'])
plt.xlabel("Basic Sanitation Access (%)")
plt.ylabel("Fetal Mortality Rate")
plt.title("Sanitation Access vs. Fetal Mortality")
plt.show()

import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import seaborn as sns

# Filter rural data
rural = wash[wash['subgroup'].str.contains('Rural', case=False, na=False)]

# Rename columns for clarity
rural = rural.rename(columns={
    "Population using basic sanitation services (%)": "basic_sanitation",
    "Population using limited sanitation services (%)": "limited_sanitation",
    "Population practising open defecation (%)": "open_defecation",
    "Population using basic drinking water services (%)": "basic_water",
    "Population using limited drinking water services (%)": "limited_water",
    "Population using unimproved drinking water services (%)": "unimproved_water",
    "Population using basic hygiene services (%)": "basic_hygiene",
    "Population using limited hygiene services (%)": "limited_hygiene",
    "Population with no hygiene services (%)": "no_hygiene"
})

# Select features + target
features = [
    "basic_sanitation", "limited_sanitation", "open_defecation",
    "basic_water", "limited_water", "unimproved_water",
    "basic_hygiene", "limited_hygiene", "no_hygiene"
]

X = rural[features]
y = rural["fetal_mortality_country_average"]

# Train/Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Random Forest Model
rf = RandomForestRegressor(n_estimators=500, random_state=42)
rf.fit(X_train, y_train)

# Feature Importance
importances = pd.Series(rf.feature_importances_, index=features).sort_values(ascending=False)

#  Exploratory Analysis
# Scatter plot: sanitation vs fetal mortality

# Plot
plt.figure(figsize=(8,5))
sns.barplot(x=importances.values, y=importances.index)
plt.title("WASH Factors Impacting Infant/Fetal Mortality (Rural Areas)")
plt.xlabel("Feature Importance")
plt.ylabel("WASH Factor")
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
import numpy as np

# Columns
hygiene_col = 'Population using basic hygiene services (%)'
mortality_col = 'fetal_mortality_country_avergage'

# Remove missing values
df_clean = df[[hygiene_col, mortality_col]].dropna()

# X and y for model
X = df_clean[[hygiene_col]]  # independent variable
y = df_clean[mortality_col]  # target

# Model
model = LinearRegression()
model.fit(X, y)

# Predictions
y_pred = model.predict(X)

# Plot
plt.figure(figsize=(8,5))
plt.scatter(X, y, color='pink', label='Data points')
plt.plot(X, y_pred, label='Regression Line')  # default color
plt.xlabel('Basic Hygiene Services (%)')
plt.ylabel('Fetal Mortality Rate')
plt.title('Linear Regression: Hygiene vs Fetal Mortality')
plt.grid(True)
plt.legend()
plt.show()

# Coefficient and intercept
print("Slope (effect):", model.coef_[0])
print("Intercept:", model.intercept_)
print("R² Score:", model.score(X, y))
